//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by JetImgCtrl.rc
//
#define IDS_JETIMGCTRL                  1
#define IDD_ABOUTBOX_JETIMGCTRL         1
#define IDB_JETIMGCTRL                  1
#define IDI_ABOUTDLL                    1
#define IDS_JETIMGCTRL_PPG              2
#define IDS_JETIMGCTRL_PPG_CAPTION      200
#define IDD_PROPPAGE_JETIMGCTRL         200
#define IDC_Magnify                     201
#define IDC_STATICCOL                   202
#define IDC_EDITCOL                     203
#define IDC_STATICROW                   204
#define IDC_EDITROW                     205
#define IDC_Magnifer                    222

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        223
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         206
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
